### ISSUE TITLE
Warning: Can't resolve all parameters for ArrayService

### ISSUE THREAD

**Issue by segux** [ng-alain/ng-alain#1753] opened 2020-07-09 08:48 UTC
- @delon/util: 9.2.1
- Angular version: 9.1.5

When i try to build my app  is throwing this warning

Warning: Can't resolve all parameters for ArrayService in /node_modules/@delon/util/util.d.ts: (?). This will become an error in Angular v6.x

**Comment by cipchk** [comment] 2020-07-19 03:41
@segux Can you provide your `tsconfig.json` and `package.json`.

**Comment by segux** [comment] 2020-07-20 10:01
Of course, Do you have any indication why it could be?
tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "inlineSources": true,
    "sourceRoot": "/",
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "preserveSymlinks": true,
    "target": "es2015",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"],
    "paths": {
      "@env/*": ["src/environments/*"],
      "@shared": ["src/app/shared/index"],
      "@shared/*": ["src/app/shared/*"],
      "@core": ["src/app/core/index"],
      "@core/*": ["src/app/core/*"],
      "@angular/*": ["node_modules/@angular/*"],
      "@ngrx/*": ["node_modules/@ngrx/*"],
      "@ngx-translate/*": ["node_modules/@ngx-translate/*"]
    }
  },
  "angularCompilerOptions": {
    "enableIvy": false
  }
}
```

package.json
```

{
  "name": "xxx",
  "version": "xxx",
  "scripts": {
   ...
},
  "private": true,
  "dependencies": {
    "@angular-builders/custom-webpack": "9",
    "@angular/animations": "~9.1.6",
    "@angular/cdk": "9.2.3",
    "@angular/common": "~9.1.6",
    "@angular/compiler": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@auth0/angular-jwt": "^4.0.0",
    "@delon/abc": "^9.2.1",
    "@delon/acl": "^9.2.1",
    "@delon/auth": "^9.2.1",
    "@delon/cache": "^9.2.1",
    "@delon/chart": "^9.2.1",
    "@delon/form": "^9.2.1",
    "@delon/mock": "^9.2.1",
    "@delon/theme": "^9.2.1",
    "@delon/util": "^9.2.1",
    "@fortawesome/fontawesome-free": "^5.11.2",
    "@ngneat/until-destroy": "^7.1.1",
    "@ngrx/store": "^9.2.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@sentry/browser": "^5.15.5",
    "@sentry/webpack-plugin": "^1.12.0",
    "@types/file-saver": "^2.0.1",
    "@types/luxon": "^1.24.0",
    "ajv": "^6.10.2",
    "angulartics2": "9",
    "angularx-qrcode": "^2.2.1",
    "bignumber.js": "^9.0.0",
    "bootstrap": "^4.3.1",
    "case": "^1.6.2",
    "clipboard-copy": "^3.1.0",
    "countries-and-timezones": "^2.2.0",
    "cryptocoins-icons": "^2.9.0",
    "file-saver": "^2.0.2",
    "hi-base32": "^0.5.0",
    "i18n-iso-639-1": "^2.0.0",
    "i18n-iso-countries": "^6.0.0",
    "iv-viewer": "^2.0.1",
    "jquery": "^3.5.1",
    "js-cookie": "^2.2.1",
    "luxon": "^1.24.1",
    "moment": "^2.25.3",
    "ng-alain": "^9.2.1",
    "ng-busy": "^9.0.0",
    "ng-zorro-antd": "9.1.1",
    "ng2-image-viewer": "^3.0.5",
    "ngx-captcha": "^8.0.1",
    "ngx-image-zoom": "^0.6.0",
    "ngx-toasta": "^1.0.3",
    "ngx-toggle-switch": "^2.0.5",
    "ngx-viewer": "^1.0.5",
    "omit-empty": "^1.0.0",
    "popper.js": "^1.16.0",
    "pretty-quick": "^2.0.1",
    "rxjs": "^6.6.0",
    "screenfull": "^5.0.0",
    "stylelint-prettier": "^1.1.1",
    "tslib": "^1.11.2",
    "tslint-config-airbnb": "^5.11.2",
    "tslint-eslint-rules": "^5.4.0",
    "tslint-plugin-prettier": "^2.0.1",
    "ua-parser-js": "^0.7.21",
    "viewerjs": "^1.5.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/cli": "~9.1.5",
    "@angular/compiler-cli": "~9.1.6",
    "@angular/language-service": "~9.1.6",
    "@angularclass/hmr": "^2.1.3",
    "@delon/testing": "^9.2.1",
    "@types/jasmine": "~3.5.10",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.149",
    "@types/node": "~13.13.5",
    "@types/omit-empty": "^1.0.0",
    "@types/ua-parser-js": "^0.7.33",
    "antd-theme-generator": "^1.2.2",
    "codelyzer": "^5.2.0",
    "country-code-lookup": "^0.0.17",
    "husky": "^4.2.5",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.2",
    "karma": "~5.0.5",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.1.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-mocha-reporter": "^2.2.5",
    "less-bundle-promise": "^1.0.7",
    "lint-staged": "^10.2.2",
    "prettier": "^2.0.5",
    "protractor": "~5.4.0",
    "puppeteer": "^3.0.4",
    "sonarqube-scanner": "^2.5.0",
    "stylelint": "^13.3.3",
    "stylelint-config-prettier": "^8.0.0",
    "stylelint-config-rational-order": "^0.1.2",
    "stylelint-declaration-block-no-ignored-properties": "^2.1.0",
    "stylelint-order": "^4.0.0",
    "tooltip.js": "^1.3.3",
    "ts-node": "~8.10.1",
    "tslint": "~6.1.2",
    "tslint-config-prettier": "^1.18.0",
    "tslint-language-service": "^0.9.9",
    "typescript": "~3.8.3"
  },
  "lint-staged": {
    "linters": {
      "src/**/*.ts": [
        "yarn run lint:ts",
        "git add"
      ],
      "src/**/*.less": [
        "yarn run lint:style",
        "git add"
      ]
    },
    "ignore": [
      "src/assets/*"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "yarn lint && pretty-quick --staged"
    }
  }
}
```

**Comment by cipchk** [comment] 2020-07-21 02:52
It may be caused by [#24414](https://github.com/angular/angular/issues/24414), but it has been fixed under lvy.

so closed it.

**Closed as completed by cipchk** 2020-07-21 02:52 UTC
